# Automatically generated by configure - do not modify
SRC_PATH=/home/andrea/Desktop/weizz/qemu-tracer/roms/vgabios
AS=as
CCAS=cc
CC=cc
BCC=bcc
CPP=cc -E
OBJCOPY=objcopy
IASL=iasl
LD=ld
RANLIB=ranlib
